apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_MOVIE_API_URL
              value: "http://ab5064f49b5a84d10b4632ea86aca791-550430836.us-east-1.elb.amazonaws.com"